Controllers/AgendaAulasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAcademia.Classes;
using WebAcademia.Models;

namespace WebAcademia.Controllers
{
    public class AgendaAulasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AgendaAulas
        public ActionResult Index()
        {
            return View(db.AgendaAulas.ToList());
        }

        // GET: AgendaAulas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgendaAulas agendaAulas = db.AgendaAulas.Find(id);
            if (agendaAulas == null)
            {
                return HttpNotFound();
            }
            return View(agendaAulas);
        }

        // GET: AgendaAulas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AgendaAulas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodigoAgendamento,HoraInicio,DuracaoMinutos")] AgendaAulas agendaAulas)
        {
            if (ModelState.IsValid)
            {
                db.AgendaAulas.Add(agendaAulas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(agendaAulas);
        }

        // GET: AgendaAulas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgendaAulas agendaAulas = db.AgendaAulas.Find(id);
            if (agendaAulas == null)
            {
                return HttpNotFound();
            }
            return View(agendaAulas);
        }

        // POST: AgendaAulas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodigoAgendamento,HoraInicio,DuracaoMinutos")] AgendaAulas agendaAulas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agendaAulas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agendaAulas);
        }

        // GET: AgendaAulas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgendaAulas agendaAulas = db.AgendaAulas.Find(id);
            if (agendaAulas == null)
            {
                return HttpNotFound();
            }
            return View(agendaAulas);
        }

        // POST: AgendaAulas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AgendaAulas agendaAulas = db.AgendaAulas.Find(id);
            db.AgendaAulas.Remove(agendaAulas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Web Academnia", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Alunos", "Index", "Alunos")</li>
                    <li>@Html.ActionLink("Aulas", "Index", "Aulas")</li>
                    <li>@Html.ActionLink("Agendamenda de Aulas", "Index", "AgendaAulas")</li>
                    <li>@Html.ActionLink("Mensalidades", "Index", "Mensalidades")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>